# Copyright (C) 2005 - 2025 Settlers Freaks <sf-team at siedler25.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Synchronize with Launchpad

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -o Acquire::Retries=3 update
          sudo apt-get -o Acquire::Retries=3 install -y openssh-client git bzr-fastimport

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: bazaar.launchpad.net
          private-key: ${{ secrets.LAUNCHPAD_PRIVATE_KEY }}

      - name: Synchronize bazaar and git
        run: |
          bzr init-repo bzr-repo
          (cd "$GITHUB_WORKSPACE" && git fast-export -M --all) | (cd bzr-repo && bzr fast-import -)

      - name: Login to launchpad
        run: bzr launchpad-login --no-check ${{ secrets.LAUNCHPAD_USER }}

      - name: Upload to launchpad
        working-directory: bzr-repo/trunk
        run: bzr push --overwrite lp:~s25rttrteam/s25rttr/s25rttr-languages
